### ISSUE TITLE
JEI Integration Missing

### ISSUE THREAD

**Issue by Davoleo** [McJty/AquaMunda#24]
Hi,
Is there Crafttweaker integration?
If yes, where can I find documentation about it?

**Comment by McJty** [comment]
Isn't it up to CT to do this? I don't think there is anything on the side of mods to do for this

**Comment by Davoleo** [comment]
Actually I think it's up to  the single mods, just because CT can't create support for every single mod, by the way I don't actually know

Ok I asked in the CT discord server, and now I'm sure of it, it's up to the modder

however is this mod going to be further developed? I've seen it's been pretty inactive lately

**Comment by McJty** [comment]
Sure it is. I just have a lot of mods to work on. But this is not abandoned.

I have no clue how to do CT support though. I'm a bit surprised it needs mod support as none of my mods have it and I'm pretty sure other people are using CT with my other mods

**Comment by jaredlll08** [comment]
He is asking for mod specific support, CraftTweaker supports nearly if not all vanilla crafting recipes and such (so adding a recipe for an item from your mod), but if you have a machine such as a custom furnace that has 2 input slots instead of 1, then you need to add support for that machine specifically.

ModTweaker does add support for some of the more popular mods and other mods even add their own support, like Immersive Engineering.

http://crafttweaker.readthedocs.io/en/latest/#Dev_Area/ZenAnnotations/ZenAnnotation/
for docs

and
https://github.com/jaredlll08/ModTweaker/blob/1.12/src/main/java/com/blamejared/compat/actuallyaddition/Crusher.java
for examples

**Comment by McJty** [comment]
Hmm. But the Aqua Munda recipes already have a configurable system on their own. i.e. you can add/remove recipes in config for all the blocks in the mod. So I think this is not needed

**Comment by Davoleo** [comment]
you're right, I missed that other config file

But, is there a way to make recipes show in JEI?
cause otherwise people will think they can't make it

**Comment by McJty** [comment]
No that's still missing. I'll reopen this ticket and rename it to 'JEI integration missing'

**Comment by Davoleo** [comment]
oh, ok, thanks for everything!

**Comment by Davoleo** [comment]
so any updates on this issue?

**Comment by McJty** [comment]
No sorry. Also hard at work at another mod for now so will be a while I'm afraid

**Comment by Davoleo** [comment]
It's ok, if I have some time to learn how jei integration works I'll maybe make a pull request for this purpose

**Comment by McJty** [comment]
Working on this now

**Comment by McJty** [comment]
Next version of AquaMunda will have JEI recipe support for the cooker, grindstone and cutting board

**Comment by Davoleo** [comment]
ok, thanks for the effort, really appreciate it!
